export const GUNTH_TITLES = [
  "GunthOS v1.0 — Veuillez ne pas éteindre votre ordinateur pendant la mise à jour",
  "GunthOS v1.0 — Approuvé par le service informatique de Gunth Corp SAS. Ils ont fait confiance une fois.",
  "GunthOS v1.0 — Chargement en cours… (depuis 1998)",
  "GunthOS v1.0 — Optimisé pour Internet Explorer 5.5 avec zoom à 125%",
  "GunthOS v1.0 — Aucun virus détecté. Vraiment. Faites-nous confiance.",
  "GunthOS v1.0 — Votre connexion 56K suffit largement",
  "GunthOS v1.0 — Redémarrage automatique programmé à 14h37. Il n'attend pas votre accord.",
  "GunthOS v1.0 — Défragmentez votre disque dur avant de continuer",
  "GunthOS v1.0 — Compatible an 2000 (sous réserve)",
  "GunthOS v1.0 — Merci de ne pas claquer la souris sur le bureau",
  "GunthOS v1.0 — Mémoire insuffisante pour charger la blague suivante. Réessayez dans 3h47.",
  "GunthOS v1.0 — Toute ressemblance avec Windows est purement intentionnelle",
  "GunthOS v1.0 — Nous ne sommes pas responsables des données perdues",
  "GunthOS v1.0 — Le pilote audio a été installé. Il ne fonctionne pas. Il est là quand même.",
  "GunthOS v1.0 — Mise à jour de sécurité disponible (ne pas installer)",
  "GunthOS v1.0 — RAM insuffisante. Fermez le Solitaire et réessayez.",
  "GunthOS v1.0 — Ce site tourne sur un Pentium II overclocked dans un sous-sol",
  "GunthOS v1.0 — Pilote introuvable. Avez-vous inséré la disquette 4 sur 27 ?",
  "GunthOS v1.0 — Nous recommandons Internet Explorer 6 pour une expérience optimale",
  "GunthOS v1.0 — Sauvegarde automatique activée. En cours depuis 3h47.",
  "GunthOS v1.0 — Dernière mise à jour : vendredi soir avant un long week-end.",
  "GunthOS v1.0 — Vous utilisez Internet Explorer. Nous ne dirons rien.",
  "GunthOS v1.0 — Votre session a expiré pendant que vous lisiez ceci.",
  "GunthOS v1.0 — Votre session a été déconnectée pendant la réunion Teams. Personne ne l'a signalé.",
  "GunthOS v1.0 — Votre demande d'accès a été transmise. En attente de validation depuis le 7 mars.",
  "GunthOS v1.0 — Sauvegarde cloud terminée. Serveur situé à Fontenay-sous-Bois. Pas de redondance.",
  "GunthOS v1.0 — Mise à jour disponible. Annulée par l'administrateur. Aucune raison communiquée.",
  "GunthOS v1.0 — Votre mot de passe expire dans 0 jours. Il a expiré pendant que vous lisiez ça.",
  "GunthOS v1.0 — Imprimante réseau introuvable. Elle est physiquement là. Elle ne répond pas.",
  "GunthOS v1.0 — Partage de fichier envoyé. Le destinataire a quitté l'entreprise hier matin.",
  "GunthOS v1.0 — Connexion VPN : établie. Déconnectée. Rétablie. Déconnectée. Elle réfléchit.",
  "GunthOS v1.0 — Rapport hebdomadaire généré automatiquement. Ouvertures depuis 2019 : 0.",
  "GunthOS v1.0 — Rappel : votre entretien annuel était prévu le 12 octobre. Nous sommes le 23 mai.",
  "GunthOS v1.0 — Le serveur de messagerie répond. Il dit non.",
  "GunthOS v1.0 — Signature électronique en attente. Elle attend depuis avant les grandes vacances.",
  "GunthOS v1.0 — Accès refusé. Demandez à votre manager. Votre manager ne sait pas non plus.",
  "GunthOS v1.0 — Votre session Teams a été coupée. La réunion a continué. Personne n'a rien dit.",
  "GunthOS v1.0 — Synchronisation OneDrive : 3 fichiers en conflit. Depuis 14 mois. Décision non prise.",
  "GunthOS v1.0 — Le formulaire a bien été soumis. Il a atterri dans le mauvais service.",
  "GunthOS v1.0 — Compatible Windows 98, 2000, ME, XP. Le reste n'est pas notre problème.",
  "GunthOS v1.0 — L'équipe support répond sous 48h. Hors jours fériés, congés et RTT accumulés.",
  "GunthOS v1.0 — Fichier joint de 47 Mo. La boîte mail du destinataire est limitée à 10 Mo.",
  "GunthOS v1.0 — Mode sans échec activé. Tout fonctionne mieux. Personne ne comprend pourquoi.",
  "GunthOS v1.0 — Le ticket de support a été clôturé automatiquement. Statut : Résolu. Ce n'est pas le cas.",
];

export const GUNTH_STATUS = [
  "💾 GunthOS v1.0 — 640 Ko de RAM libres. Fermez le Solitaire avant de continuer.",
  "💾 GunthOS v1.0 — Défragmentation en cours… 2% (temps restant : 6h)",
  "💾 GunthOS v1.0 — Aucun périphérique inconnu détecté. Pour l'instant.",
  "💾 GunthOS v1.0 — Sauvegarde automatique… terminée. Ou pas.",
  "💾 GunthOS v1.0 — Disque C:\\ presque plein. Supprimez des fichiers système.",
  "💾 GunthOS v1.0 — Mise à jour du pilote de souris : redémarrage dans 3, 2… jamais.",
  "💾 GunthOS v1.0 — Registre corrompu sur 3 des 4 ruches système. La 4ème est introuvable.",
  "💾 GunthOS v1.0 — Mémoire virtuelle faible. Ouvrez quand même 12 onglets.",
  "💾 GunthOS v1.0 — Analyse antivirus : vous avez 47 virus. Bonne journée !",
  "💾 GunthOS v1.0 — Erreur générale de protection. Ignorée avec succès.",
  "💾 GunthOS v1.0 — Processus inconnu 'gunth.exe' consomme 98% du CPU. Il ne répond pas aux questions.",
  "💾 GunthOS v1.0 — Dernière défragmentation : 1999. Fragmentation actuelle : artistique.",
  "💾 GunthOS v1.0 — Réunion Teams en cours. 14 participants. 13 en sourdine. Le 14ème partage son écran par accident depuis 47 minutes.",
  "💾 GunthOS v1.0 — PID 666 : actif. A refusé l'invitation au stand-up. A raison.",
  "💾 GunthOS v1.0 — Ticket JIRA-2847 ouvert le 14 janvier 2002. Statut : In Progress. Assigné : personne. Priorité : bloquante.",
  "💾 GunthOS v1.0 — VPN : connecté. Déconnecté. Reconnecté. Déconnecté. Il réfléchit toujours.",
  "💾 GunthOS v1.0 — Impression en cours depuis 3h47. Clignote en orange. Ne touchez à rien.",
  "💾 GunthOS v1.0 — Quota boîte mail dépassé. Dernier mail reçu : 'Re: Re: Re: FWD: Réunion annulée'.",
  "💾 GunthOS v1.0 — Windows Update : redémarrage forcé dans 4 minutes. Vous n'avez pas sauvegardé.",
  "💾 GunthOS v1.0 — Erreur 404 sur le serveur interne. Depuis 2004. Ticket non ouvert.",
  "💾 GunthOS v1.0 — Mode économie d'énergie activé. Il consomme plus que le mode normal.",
  "💾 GunthOS v1.0 — 3 processus zombies détectés. Dont PID 666. Il est le doyen. Il mérite le respect.",
  "💾 GunthOS v1.0 — Sauvegarde auto : active. Destination : dossier Temp. Supprimé au redémarrage.",
  "💾 GunthOS v1.0 — Fichier 'FINAL_v3_VRAIMENT_FINAL_2.xlsx' ouvert par 3 utilisateurs simultanément. Conflits à venir.",
  "💾 GunthOS v1.0 — Connexion SMTP impossible. Vos mails sont dans la tête de l'ordinateur pour l'instant.",
  "💾 GunthOS v1.0 — Corbeille : 2,4 Go. Dont 2 Go de fichiers 'au cas où' qui datent de 2007.",
  "💾 GunthOS v1.0 — Pilote d'imprimante réinstallé. L'imprimante reste introuvable. C'est une tradition.",
];

export const GUNTH_SHUTDOWN_MESSAGES = [
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nVos 47 onglets non sauvegardés seront perdus. Notamment le formulaire que vous remplissiez depuis 20 minutes.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nNous vous recommandons de retirer la disquette du lecteur avant de partir.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nN'oubliez pas de souffler dans la cartouche avant de rallumer.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nErreur lors de la préparation de l'arrêt. L'arrêt aura quand même lieu.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nVos données non sauvegardées ont été conservées en lieu sûr. (C'est faux.)",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nApplication de 0 mise à jour critique. Pour une fois.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nGunthOS vous remercie de l'avoir utilisé. Il ne le pense pas vraiment.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nLe processus mystérieux (PID 666) est toujours en cours. Vous êtes prévenu(e).",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nDéfragmentation du disque recommandée avant l'arrêt. Temps estimé : 6h.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nAucune sauvegarde automatique n'a été effectuée. Bonne chance.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nLe processus svchost.exe (×23) va se terminer. Personne ne sait ce qu'il fait. Personne ne posera la question.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nMicrosoft vous rappelle d'éteindre correctement votre ordinateur. GunthOS vous rappelle que ça ne change rien.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nVotre badge d'onboarding n'a toujours pas été activé. Le service informatique répond sous 47 jours ouvrés. Ce n'est pas une blague.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nLa revue de roadmap débute dans 3 minutes. Votre présence est 'vivement recommandée'. GunthOS sait ce que ça veut dire.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nVotre fichier 'FINAL_v2_CORRIGE_BIS.xlsx' contient des modifications non sauvegardées. Depuis 3h47. Nous ne dirons rien.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nUne mise à jour a été téléchargée. Elle s'installera pendant l'arrêt. Elle cassera quelque chose. On ne sait pas encore quoi.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nVotre VPN va se déconnecter. Il était déjà déconnecté depuis 40 minutes. Votre réunion se passait quand même.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nL'imprimante réseau est disponible pour la première fois depuis octobre. Elle ne le sera plus à votre prochaine connexion.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nLe reporting mensuel est en cours. Il manque 3 chiffres. Les 3 chiffres attendent une réponse de Tonton Roger depuis jeudi.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nCette action nécessite les droits administrateur. L'administrateur est Gilles. Gilles est en congé paternité.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nAucune sauvegarde distante configurée. Votre travail existe uniquement dans la RAM. Et dans votre espoir.",
  "Êtes-vous sûr(e) de vouloir éteindre GunthOS ?\n\nVos préférences d'accessibilité seront réinitialisées. Elles n'avaient de toute façon jamais été appliquées correctement.",
];

export const GUNTH_REBOOT_MESSAGES = [
  "GunthOS redémarre…\n\nVeuillez patienter pendant que nous prétendons réparer quelque chose.",
  "GunthOS redémarre…\n\nC'est souvent la solution à tous les problèmes.",
  "GunthOS redémarre…\n\nNe touchez à rien. Surtout pas à ça.",
  "GunthOS redémarre…\n\nApplication de 47 mises à jour critiques. (c'est un mensonge)",
  "GunthOS redémarre…\n\nDéfragmentation du cerveau en cours. Cela peut prendre un moment.",
  "GunthOS redémarre…\n\nFermeture de 23 processus orphelins. Ils ne manqueront à personne.",
  "GunthOS redémarre…\n\nNettoyage du cache. Les 2 Go de miniatures JPEG de 2002 ont été conservés par précaution.",
  "GunthOS redémarre…\n\nRecalibrage du noyau. Résultat attendu : identique à avant. C'est rassurant.",
  "GunthOS redémarre…\n\nVotre ticket de support a été automatiquement clôturé pendant l'arrêt. Statut : 'Résolu'. Ce n'est pas le cas.",
  "GunthOS redémarre…\n\nToutes vos fenêtres seront restaurées. Dans un état légèrement différent. Aucune garantie.",
  "GunthOS redémarre…\n\nApplications au démarrage : 23 programmes vont se lancer. Vous n'en avez installé aucun consciemment.",
  "GunthOS redémarre…\n\nL'horloge système a 3 minutes de retard. Elle a toujours eu 3 minutes de retard. On a arrêté de corriger ça en 2003.",
  "GunthOS redémarre…\n\nVérification du disque : 3 erreurs trouvées. Corrigées. 7 nouvelles erreurs créées dans le processus.",
  "GunthOS redémarre…\n\nLa barre des tâches va s'afficher à droite de l'écran. Sans raison. Comme toujours.",
  "GunthOS redémarre…\n\nVos favoris Internet Explorer ont été conservés. Ils pointent vers des sites disparus en 2006. Mais ils sont là.",
  "GunthOS redémarre…\n\nGilles a été notifié du redémarrage. Gilles ne sait pas pourquoi. Gilles est en congé paternité de toute façon.",
];

export const PEGGLE_TIPS = [
  "Cliquez pour tirer • votre précision est… caractéristique.",
  "Cliquez pour tirer • les pegs orange prient pour vous. Ça ne suffira pas.",
  "Cliquez pour tirer • l'IA a calculé votre score optimal. Elle ne le dira pas.",
  "Cliquez pour tirer • ce niveau a été terminé en 3 coups. Pas par vous.",
  "Cliquez pour tirer • fermer les yeux ne change rien. C'est reposant quand même.",
  "Cliquez pour tirer • le record est 847 points. Bon courage.",
  "Cliquez pour tirer • appuyer plus fort ne sert à rien. Mais continuez.",
  "Cliquez pour tirer • la physique est configurable. Demandez à l'admin.",
  "Cliquez pour tirer • essayez de viser. Pour changer.",
  "Cliquez pour tirer • un enfant de 7 ans a fini ce niveau. Une seule fois. Mais quand même.",
  "Cliquez pour tirer • les pegs bleus sont là pour vous donner de l'espoir. C'est leur seul rôle.",
  "Cliquez pour tirer • le niveau suivant est légèrement plus difficile. Comme chaque semaine en entreprise.",
  "Cliquez pour tirer • la trajectoire a été calculée par l'IA. Elle ne garantit rien. Ni vous.",
  "Cliquez pour tirer • Jean-Kévin a terminé ce niveau. Il en a fait un post LinkedIn. 847 réactions.",
  "Cliquez pour tirer • le multiplicateur de score ne s'active que si vous regardez ailleurs.",
  "Cliquez pour tirer • Sandrine R. observe votre score depuis le début. Elle ne dira rien.",
  "Cliquez pour tirer • niveau 47 : débloqué. Niveau 48 : en développement depuis 2003.",
  "Cliquez pour tirer • appuyer fort n'aide pas. Mais ça soulage. C'est déjà ça.",
];


export const PROFILE_SAVE_MESSAGES = [
  "✅ Profil sauvegardé. Personne ne lira votre bio mais elle est là.",
  "✅ Modifications enregistrées. Le serveur a haussé les épaules.",
  "✅ Sauvegardé sur le cloud (un Raspberry Pi dans un placard à Roubaix).",
  "✅ Profil compressé en ZIP protégé par un mot de passe qu'on a oublié.",
  "✅ Données inscrites sur bande magnétique. Quelque part dans un tiroir.",
  "✅ Sauvegardé dans C:\\USERS\\MOI\\PROFIL.txt",
  "✅ Mis à jour. L'ancienne version est conservée par sécurité. (Non.)",
  "✅ Profil mis à jour. Le cache se vide dans 24h. Vous verrez l'ancienne version jusqu'à demain.",
  "✅ Sauvegardé. La photo sera redimensionnée à 47×47 pixels à l'affichage.",
  "✅ Modifications enregistrées. Synchronisation avec le Minitel 3617 GUNTH en cours.",
  "✅ Sauvegardé sur bande magnétique dans un datacenter à Mulhouse.",
  "✅ Une copie de sauvegarde a été envoyée à Mamie Huguette par mesure de sécurité.",
  "✅ Profil compressé avec WinZip 7.0. Mot de passe : votre date de naissance en DDMMYYYY.",
  "✅ Données persistées. Gilles validera manuellement avant publication. Gilles est en congé.",
  "✅ Mis à jour. L'ancien profil est archivé sur une disquette en lieu sûr. La disquette est introuvable.",
];

export const SETTINGS_RAM_STATUSES = [
  "Mémoire : suffisante (ne demandez pas pour combien de temps)",
  "RAM : au bord du gouffre. Fermez le Solitaire.",
  "RAM : 640 Ko de libres. C'est largement suffisant pour 1998.",
  "Mémoire virtuelle : en swap depuis 2002. Tout va bien.",
  "RAM libre : 47 Ko. Évitez d'ouvrir quoi que ce soit.",
  "Mémoire : optimisée par l'IA (résultats non garantis, remboursements refusés)",
  "RAM : en lecture intensive d'un fichier corrompu depuis le démarrage",
  "Mémoire : 12 onglets ouverts dont 9 inutiles. Vous le savez. Continuez.",
  "RAM : suffisante maintenant. Insuffisante dans 3 minutes.",
  "Mémoire virtuelle : étendue à D:\\ qui n'existe pas. Ça fonctionne quand même.",
  "RAM libre : moins qu'au démarrage, plus qu'à l'arrêt. Le reste est un mystère.",
  "Mémoire : fragmentée comme votre agenda de la semaine. Défragmentation non conseillée.",
];

export const SETTINGS_LICENSES = [
  "Licence : expirée en 2002",
  "Licence : en cours de renouvellement depuis 1999",
  "Licence : transmise oralement de père en fils",
  "Licence : achetée avec des points de fidélité Carrefour",
  "Licence : creative commons © Gunth Corp™ — tous droits flous",
  "Licence : shareware — payez si l'envie vous prend",
  "Licence : aucune. Assumée.",
  "Licence : validée par un stagiaire en août 2001. Le stagiaire ne travaille plus là.",
  "Licence : GNU GPL v2 — mal interprétée depuis 20 ans",
  "Licence : offerte avec l'achat d'un PC Packard Bell. Le PC est mort. La licence résiste.",
  "Licence : transmise par email depuis une adresse Caramail supprimée en 2009",
  "Licence : shareware — 30 jours d'essai dépassés en 2003. On a continué.",
  "Licence : gravée sur CD-ROM dans le tiroir du bas à côté d'une pile plate",
];

export const GUNTHER_STATUS_BAR_MSGS = [
  "Sprint 47 • Vélocité : 0 • Moral : stable",
  "Prochaine démo : vendredi • Préparation : 0%",
  "Stand-up : 14h • Durée estimée : 3h • Café : nécessaire",
  "Burndown chart : en feu",
  "Dernier déploiement : jamais • Prochain : bientôt™",
  "Mode Kanban™ activé • Fonctionnalité en bêta depuis 2001",
  "Tickets perdus : ∞ • Tickets trouvés : 0 • Équipe : occupée",
  "Roadmap : confidentielle • Deadline : hier",
  "Ticket JIRA-∞ • Priorité : critique • Assigné : Sandrine R. • Sandrine R. a quitté l'entreprise en 2019",
  "Onboarding J+47 • Badge : désactivé • Manager : en déplacement • WiFi : inconnu",
  "Réunion Teams • Lien envoyé • Lien expiré • Nouveau lien en cours depuis 23 min",
  "Sprint Inception • Vélocité : à définir • Définition de 'fait' : à définir • Tout : à définir",
  "Réunion de sprint annulée • Réunion pour annuler la réunion : confirmée • 14h",
  "Ticket sans description • Priorité : max • Deadline : hier • Auteur : compte supprimé",
  "Burndown chart : vertical • Équipe : optimiste • Réalité : autre chose",
  "Démo client vendredi • Fonctionnalité : 12% faite • Slides : 100% prêts",
  "Rétrospective • Ce qui a marché : la bonne humeur • Ce qui n'a pas marché : le reste",
  "Story points : 47 • Livrés : 3 • Restants : on verra • Moral : en cours",
  "PID 666 • Aucun sprint • Personne ne sait ce qu'il fait • Là depuis 1998",
  "Kanban bloqué • Colonne 'En cours' : 47 tickets • Colonne 'Fait' : 0 • Ambiance : studieuse",
  "Ticket rouvert • Par quelqu'un qui ne savait pas qu'il était résolu • Assigné : personne",
];

export const GUNTHER_LOADING_HINTS = [
  "(Le stand-up a pris du retard.)",
  "(La story-pointing de cette tâche dure depuis 3h.)",
  "(Le serveur est en télétravail aujourd'hui.)",
  "(Sprint en cours. Les tickets pas vraiment.)",
  "(Synchronisation avec les volontés de l'univers.)",
  "(Le kanban réfléchit à sa vie.)",
  "(Le serveur fait ce qu'il peut. Ce n'est pas beaucoup.)",
  "(Le ticket a été rouvert par quelqu'un qui ne savait pas qu'il était résolu.)",
  "(Le manager bienveillant prépare un feedback constructif. Depuis le 3 octobre.)",
  "(La réunion de cadrage de la réunion de cadrage est planifiée pour jeudi prochain.)",
  "(Le sprint review a été annulé. La réunion pour planifier le sprint review aussi.)",
  "(Le client a changé d'avis pendant le stand-up.)",
  "(Cette story a été estimée 3 fois. Trois estimations différentes. Aucune correcte.)",
  "(L'équipe est 'full capacity' depuis 18 mois. La capacity n'a jamais été calculée.)",
  "(Le bug est 'non reproductible'. Il se reproduit en production deux fois par jour.)",
  "(La documentation sera faite 'après'. Après n'a pas encore eu lieu.)",
  "(Le déploiement est planifié pour jeudi. Le rollback est planifié pour vendredi.)",
  "(Le Product Owner est 'disponible'. Il n'a pas répondu depuis mardi.)",
  "(L'environnement de recette diffère de la prod. On ne sait pas depuis quand.)",
  "(Le ticket a été fermé automatiquement après 30 jours. Le bug est toujours là.)",
];

export const DIRECTORY_LOADING_MSGS = [
  "Chargement de la liste des gens qui existent...",
  "Interrogation du bottin 3617 GUNTH en cours...",
  "Requête envoyée. Réponse attendue avant lundi.",
  "Chargement des profils depuis la disquette...",
  "Récupération de l'annuaire pages jaunes...",
  "Synchronisation des utilisateurs avec le serveur de 1998...",
  "Consultation du fichier Cegetel en cours...",
  "Chargement de l'annuaire papier numérisé en 72 dpi...",
  "Connexion au serveur d'annuaire via modem 28.8k...",
  "Récupération des profils depuis le Minitel 3617 GUNTH...",
  "Synchronisation avec l'annuaire du CE Carrefour...",
  "Transmission télégraphique des données utilisateur en cours...",
];

export const DIRECTORY_EMPTY_SEARCH_MSGS = [
  "Introuvable. Cette personne a peut-être changé de nom pour vous éviter.",
  "0 résultat. Vérifiez que vous connaissez vraiment leur prénom.",
  "Personne par ce nom. Le secteur disque est peut-être corrompu.",
  "Aucun résultat. Essayez d'être moins précis.",
  "Introuvable. Mais la recherche a quand même été décomptée.",
  "Cet utilisateur n'existe pas — ou s'est défragmenté depuis.",
  "Aucun résultat. Avez-vous essayé avec le nom de jeune fille ?",
  "Introuvable. Ce profil a peut-être été défragmenté lors de la dernière mise à jour.",
  "0 résultat. La bande magnétique est peut-être saturée.",
  "Personne par ce nom. Il est possible qu'elle utilise un pseudonyme. Ou qu'elle n'existe pas.",
  "Aucun utilisateur correspondant. Vérification du nom, prénom, commune, département.",
  "Introuvable sur ce serveur. Essayez celui de Roubaix. Il répond parfois.",
];

export const DIRECTORY_NO_USERS_MSGS = [
  "Aucun utilisateur inscrit. Soyez le premier — ou pas.",
  "Annuaire vide. Le serveur se sent seul.",
  "0 membre. Le modem est probablement débranché.",
  "Personne ici. Plus vide que votre corbeille après une grosse semaine.",
  "L'annuaire existe. Les habitants, non.",
  "Annuaire vide. Premier arrivé, premier servi. Le serveur attend depuis 1998.",
  "Aucun membre enregistré. L'annuaire existait avant les utilisateurs. Comme souvent.",
  "0 profils disponibles. Le badge d'accès à l'annuaire n'a pas encore été activé.",
  "Personne ici. Comme la réunion du lundi matin avant 9h20.",
];

export const LNK_POST_PUBLISH_TOASTS = [
  "📈 Post publié. L'algorithme va décider si vous existez.",
  "🚀 Publié ! Vos 3 relations l'ont vu. L'une d'elles était vous.",
  "✅ En ligne ! Sandrine est en train de rédiger 'Tellement vrai.'",
  "📣 Diffusé dans le vide professionnel. Quelqu'un réagira avec 🙏",
  "🚀 Post live ! Jean-Kévin l'a déjà partagé sans le lire.",
  "📈 Publié. L'algorithme analyse votre potentiel viral. Résultat : modeste.",
  "🚀 En ligne. Jean-Kévin a réagi 'Inspirant' sans ouvrir le post.",
  "✅ Post diffusé. Tonton Roger l'a vu. Il ne comprend pas ce qu'est LinkedGunth mais il est là.",
  "📣 Publié à 14h37. Heure statistiquement la moins active de votre réseau. Bon courage.",
  "🚀 En direct. Mamie Huguette a aimé. Sandrine R. lit mais ne réagit pas.",
  "📈 Live. 3 personnes l'ont déjà signalé. Votre authenticité les a dérangées.",
  "✅ Publié. L'algorithme a décidé de ne pas le montrer à vos abonnés par précaution.",
  "🚀 Diffusé dans l'éther professionnel. Quelqu'un va s'en inspirer sans vous citer.",
];

export const LNK_AI_TOASTS = [
  "🤖 L'IA a authentifié votre authenticité de manière authentique.",
  "✨ Post rédigé en 1,1s par une IA formée sur 10 000 posts LinkedIn. Ça se voit.",
  "🧠 Thought leadership généré automatiquement. Comme toujours.",
  "🤖 Contenu co-écrit avec une IA qui ne vous connaît pas du tout.",
  "✨ Votre essence disrupto-bienveillante a été capturée par l'algorithme.",
  "🤖 Authenticité simulée avec succès. Personne ne verra la différence.",
  "🤖 Post généré par une IA qui n'a pas vécu votre expérience. Ça ne se voit pas trop.",
  "✨ Authenticité augmentée à 94% par l'IA. Les 6% restants sont vous.",
  "🧠 L'IA a remplacé 'synergies' par 'synergie' au singulier. C'est plus disruptif.",
  "🤖 Rédigé en 0,8 secondes. Basé sur vos 47 posts précédents. Vous vous répétez.",
  "✨ L'IA a détecté une potentielle controverse et l'a retirée. Votre authenticité est maintenant inoffensive.",
  "🧠 Post co-écrit avec l'IA. L'IA a fait 97% du travail. Vous avez choisi l'emoji.",
  "🤖 Votre voix unique a été capturée, optimisée, et rendue indiscernable de 12 000 autres profils.",
  "✨ Thought leadership généré. Originalité détectée : 2%. Ça suffira.",
];

export const LNK_CONNECTION_TOASTS: ((n: number) => string)[] = [
  (n) => `🤝 Connexion acceptée ! Vous avez maintenant ${n} relations.`,
  (n) => `🤝 +1 relation. ${n} personnes dont vous ne connaissez pas les prénoms.`,
  (n) => `🤝 Accepté(e) ! ${n} relations. Qualité non vérifiée.`,
  (n) => `🤝 Réseau étendu à ${n} personnes. La carrière va décoller. Sûrement.`,
  (n) => `🤝 ${n} relations maintenant. Sandrine R. prend note.`,
  (n) => `🤝 +1 relation. ${n} relations au total. Dont Tonton Roger, jamais connecté.`,
  (n) => `🤝 Accepté(e). ${n} relations dont vous ne vous souvenez plus des visages.`,
  (n) => `🤝 Réseau étendu à ${n}. Mamie Huguette va recevoir vos posts en notification SMS.`,
  (n) => `🤝 +1. ${n} relations. Jean-Kévin va commenter dans les 4 minutes. Chronomètre.`,
  (n) => `🤝 Connexion acceptée. ${n} personnes dans votre réseau. Dont 47 inactives depuis 2021.`,
];

export const PUBLIC_PROFILE_LOADING_MSGS = [
  "Connexion 56K en cours...",
  "Transmission par satellite géostationnaire...",
  "Chargement via le réseau RNIS 64K...",
  "Téléchargement du profil depuis le FTP de 1998...",
  "Synchronisation avec le serveur de données humaines...",
  "Rapatriement du profil depuis la disquette de sauvegarde...",
  "Connexion à l'annuaire via carte PCMCIA en cours...",
  "Rapatriement du profil par Chronopost express...",
  "Interrogation du serveur Cegetel en cours...",
  "Chargement via réseau Token Ring...",
  "Récupération depuis la disquette de secours numérotée...",
  "Transmission par fax inversé depuis la base de données...",
];

export const PUBLIC_PROFILE_NOT_FOUND_MSGS = [
  "n'existe pas ou a été défragmenté.",
  "a peut-être changé d'identité numérique.",
  "a été effacé lors d'une mise à jour du registre.",
  "est introuvable. Secteur disque : corrompu.",
  "n'a jamais existé ici. Ou a existé et a disparu. Les deux sont plausibles.",
  "a peut-être changé de nom suite à un mariage ou une fusion-acquisition.",
  "était là. Le secteur disque a été réalloué depuis.",
  "n'a pas encore rempli le formulaire d'existence en triple exemplaire.",
  "est en cours de migration vers le nouveau serveur. Depuis le 14 janvier 2002.",
];
