export const BOT_COMMENTERS = [
  { name: "Patrick Lemaire", avatar: "🦁" },
  { name: "Jean-Kévin M.", avatar: "👔" },
  { name: "Nadège B.", avatar: "🌸" },
  { name: "Thierry C.", avatar: "🎯" },
  { name: "Sandrine R.", avatar: "💼" },
  { name: "Marc Technologie", avatar: "🚀" },
  { name: "Sophie LB.", avatar: "🌟" },
  { name: "Beatrix von S.", avatar: "🧘" },
  { name: "Gilles P.", avatar: "💡" },
  { name: "Amandine K.", avatar: "🌈" },
  { name: "Rodrigo M.", avatar: "🔥" },
  { name: "Françoise D.", avatar: "🦋" },
  { name: "Christophe V.", avatar: "⚡" },
  { name: "Ingrid L.", avatar: "🎯" },
  { name: "David Startup", avatar: "🦄" },
  { name: "Nathalie C.", avatar: "🌺" },
  { name: "Kevin (pas Jean)", avatar: "😤" },
  { name: "Isabelle Burnout", avatar: "🕯️" },
  { name: "Stéphane 🇫🇷", avatar: "🏆" },
  { name: "Moussa D.", avatar: "💪" },
  { name: "Caroline Pivot", avatar: "🔄" },
  { name: "Jérôme Ex-GAFA", avatar: "🍎" },
  { name: "Laure Bienveillante", avatar: "🤗" },
  { name: "Didier Agile", avatar: "📌" },
  { name: "Virginie W.", avatar: "✨" },
  { name: "Cédric Le Disrupteur", avatar: "💥" },
  { name: "Pauline Coach", avatar: "🧭" },
  { name: "Thomas T.", avatar: "🎖️" },
  { name: "Muriel 2.0", avatar: "🤖" },
  { name: "Luc Résilient", avatar: "🌱" },
  { name: "François-Xavier B.", avatar: "🎻" },
  { name: "Ophélie Momentum", avatar: "🌊" },
  { name: "Renaud Q.", avatar: "🦅" },
  { name: "Delphine Sans-Titre", avatar: "🪴" },
  { name: "Maxime B2B", avatar: "📈" },
  { name: "Tanguy Le Curieux", avatar: "🔍" },
  { name: "Aline Onboarding", avatar: "🎯" },
  { name: "Greg (ex-McKinsey)", avatar: "💰" },
  { name: "Yasmine Top5%", avatar: "🏅" },
  { name: "Bernard Disruption", avatar: "🌋" },
  { name: "Nadia Holistic", avatar: "🔮" },
  { name: "Romain Scale", avatar: "📐" },
  { name: "Estelle Authentic", avatar: "🌻" },
  { name: "Hubert V.", avatar: "🎱" },
  { name: "Océane No-Code", avatar: "⚙️" },
  { name: "Sylvain Keynote", avatar: "🎤" },
  { name: "Dorothée Impact", avatar: "🌍" },
  { name: "Alexis Blockchain", avatar: "⛓️" },
  { name: "Marlène Feedback", avatar: "📝" },
  { name: "Florent 360°", avatar: "🔁" },
  { name: "Annick Reconvertie", avatar: "🦚" },
  { name: "Raphaël No-Drama", avatar: "🕊️" },
  { name: "Charline Metaverse", avatar: "🥽" },
  { name: "Lionel Territoire", avatar: "🗺️" },
  { name: "Gwenaëlle Woke RH", avatar: "✊" },
  { name: "Mehdi Product", avatar: "🧩" },
  { name: "Véronique Transfo", avatar: "🦠" },
  { name: "Bastien Frugal", avatar: "🪨" },
  { name: "Audrey AI-First", avatar: "🤯" },
  { name: "Jacques-Henri M.", avatar: "🧣" },
  { name: "Svetlana B.", avatar: "🌷" },
  { name: "Pierrick Synapse", avatar: "🧬" },
  { name: "Magalie Slow", avatar: "🐢" },
  { name: "Gontran F.", avatar: "🎠" },
  { name: "Cindy Influence", avatar: "💅" },
  { name: "Rémi sans H", avatar: "🤷" },
  { name: "Dominique (H ou F)", avatar: "🌀" },
  { name: "Armand Networking", avatar: "🕸️" },
  { name: "Laurence 2.0", avatar: "🖨️" },
  { name: "Théo Ex-HEC", avatar: "🎓" },
  { name: "Séverine Burnin", avatar: "🔦" },
  { name: "Jérémy Side-Project", avatar: "🛸" },
  { name: "Monique Digitale", avatar: "💾" },
  { name: "Xavier Le Pionnier", avatar: "🧭" },
  { name: "Elodie Sens", avatar: "🕯️" },
  { name: "Fernand Agile", avatar: "🧶" },
  { name: "Wendeline K.", avatar: "🦜" },
  { name: "Patrice Intrapreneur", avatar: "🏗️" },
  { name: "Cassandre V.", avatar: "🔮" },
] as const;

export const BOT_VISITORS = [
  { name: "Patrick Lemaire", title: "CEO · Fondateur · Disrupteur", emoji: "🦁" },
  { name: "Nadège Blondel", title: "Coach de vie · Speaker · Maman de 3", emoji: "🌸" },
  { name: "Jean-Kévin M.", title: "Growth Hacker en devenir", emoji: "🚀" },
  { name: "Thierry Consultant", title: "Expert en tout · Consultant indépendant", emoji: "👔" },
  { name: "Bruno Disruptif", title: "Head of Head of Head of Things", emoji: "🧠" },
  { name: "Sophie L-B", title: "Directrice de la Direction Directoriale", emoji: "💼" },
  { name: "Marc Technologie", title: "Digital Transformer · Speaker TEDx refusé", emoji: "📱" },
  { name: "Karine R.", title: "Top Voice™ · Influenceuse B2B", emoji: "⭐" },
  { name: "Arnaud Pivot", title: "Entrepreneur · Passionné par les synergies", emoji: "🔄" },
  { name: "Véronique S.", title: "Manager Agile · Agilité sur CV depuis 2019", emoji: "📊" },
  { name: "Gilles Passion", title: "Je transforme les problèmes en opportunités · Solopreneur", emoji: "💡" },
  { name: "Amandine K.", title: "Chief Happiness Officer · Yoga du rire certifiée", emoji: "🌈" },
  { name: "Rodrigo M.", title: "Founder · Serial Entrepreneur · 3 exits (dont 1 raté)", emoji: "🔥" },
  { name: "Françoise D.", title: "Reconvertie · Anciennement RH · Maintenant moi-même", emoji: "🦋" },
  { name: "Christophe V.", title: "CEO & Janitor · Bootstrapped · Fier", emoji: "⚡" },
  { name: "Ingrid L.", title: "NLP Practitioner · Coach holistique · Numerologue", emoji: "🎯" },
  { name: "David Startup", title: "Building the next unicorn (en cours) · Ex-ESSEC", emoji: "🦄" },
  { name: "Nathalie C.", title: "Experte en transformation par l'écoute active", emoji: "🌺" },
  { name: "Kevin (pas Jean)", title: "Dev fullstack · Open to work · 3 ans XP", emoji: "😤" },
  { name: "Isabelle Burnout", title: "Après 15 ans en corporate, j'ai tout plaqué 🙏", emoji: "🕯️" },
  { name: "Stéphane 🇫🇷", title: "Commercial B2B · Champion du monde du networking", emoji: "🏆" },
  { name: "Moussa D.", title: "Entrepreneur · Mentor · Passionné de football ET de business", emoji: "💪" },
  { name: "Caroline Pivot", title: "Reconversion pro · De comptable à consultante en sens", emoji: "🔄" },
  { name: "Jérôme Ex-GAFA", title: "Ancien de Google · Maintenant libre · Vraiment libre", emoji: "🍎" },
  { name: "Laure Bienveillante", title: "Manager bienveillante · 0 conflit depuis 2021", emoji: "🤗" },
  { name: "Didier Agile", title: "Scrum Master · Kanban · SAFe · LeSS · DAD · Tout", emoji: "📌" },
  { name: "Virginie W.", title: "Personal Branding · Vous méritez un meilleur LinkedIn", emoji: "✨" },
  { name: "Cédric Le Disrupteur", title: "I don't think outside the box. I burn the box.", emoji: "💥" },
  { name: "Pauline Coach", title: "Coach ICF · PNL · Ikigai · Ennéagramme · MBTI (ENFJ)", emoji: "🧭" },
  { name: "Thomas T.", title: "Scale-up advisor · Board member · Investisseur passif", emoji: "🎖️" },
  { name: "Muriel 2.0", title: "DRH 3.0 · Future of Work · Chief People de moi-même", emoji: "🤖" },
  { name: "Luc Résilient", title: "Tombé 7 fois, levé 8 · Marathon · Mindfulness", emoji: "🌱" },
  { name: "Béatrice Von S.", title: "Leadership féminin · Yoga exécutif · Lausanne", emoji: "🧘" },
  { name: "Éric Le Visionnaire", title: "Visionnaire confirmé · 2 brevets · 0 revenue", emoji: "🔭" },
  { name: "Sandra Authentic", title: "J'arrête de me cacher. Voici ma vraie histoire. 🧵", emoji: "🧵" },
  { name: "François-Xavier B.", title: "Avocat · Associé · Père de famille · Coureur (lent)", emoji: "🎻" },
  { name: "Ophélie Momentum", title: "Je crée du momentum. Pas du bruit. Du momentum.", emoji: "🌊" },
  { name: "Renaud Q.", title: "Fondateur · Visionnaire · En train de manger une pomme", emoji: "🦅" },
  { name: "Delphine Sans-Titre", title: "Entre deux postes · En pleine déconstruction · Bien.", emoji: "🪴" },
  { name: "Maxime B2B", title: "Sales Director · Pipeline · Funnel · Quota · Répéter", emoji: "📈" },
  { name: "Tanguy Le Curieux", title: "Je pose des questions. Toujours. C'est mon super-pouvoir.", emoji: "🔍" },
  { name: "Aline Onboarding", title: "J'ai onboardé 300 personnes. Aucune n'est repartie. (3 sont partis)", emoji: "🎯" },
  { name: "Greg (ex-McKinsey)", title: "Ex-McKinsey · Ex-Bain · Ex-BCG · Actuellement disponible", emoji: "💰" },
  { name: "Yasmine Top5%", title: "Top 5% LinkedIn France 2023 · Top 5% 2024 · En route pour 2025", emoji: "🏅" },
  { name: "Bernard Disruption", title: "Je dis 'disruption' dans chaque phrase. C'est ma marque.", emoji: "🌋" },
  { name: "Lucie Sans-Bureau", title: "Full remote · No meeting Fridays · No meeting Thursdays · Hmm", emoji: "🏖️" },
  { name: "Antoine Consensus", title: "Manager · J'aligne les parties prenantes depuis 2008", emoji: "🤝" },
  { name: "Hélène Portefeuille", title: "Portfolio career · 4 casquettes · 0 description claire", emoji: "🎩" },
  { name: "Cyril MVP", title: "Je ship des MVPs · Vite · Très vite · Parfois trop vite", emoji: "💨" },
  { name: "Véga R.", title: "Né pour entreprendre · Je l'ai su à 7 ans · Mon prof pas convaincu", emoji: "⭐" },
  { name: "Nadia Holistic", title: "Santé holistique en entreprise · Le corps parle · J'écoute", emoji: "🔮" },
  { name: "Romain Scale", title: "Scale-up · Scale-down · Scale-out · Scale-anywhere · Scale", emoji: "📐" },
  { name: "Estelle Authentic", title: "Je ne joue plus de rôle. Même au boulot. Surtout au boulot.", emoji: "🌻" },
  { name: "Hubert V.", title: "Président de chambre de commerce · Bénévole · Golf (hcp 12)", emoji: "🎱" },
  { name: "Océane No-Code", title: "J'ai créé 3 apps sans coder. ChatGPT compte ?", emoji: "⚙️" },
  { name: "Sylvain Keynote", title: "Conférencier · 47 keynotes · 3 debriefs · 0 encore", emoji: "🎤" },
  { name: "Dorothée Impact", title: "Impact positif · Impact négatif évité · Impact mesuré (parfois)", emoji: "🌍" },
  { name: "Alexis Blockchain", title: "Web3 evangelist · NFT collector · Actuellement en deuil", emoji: "⛓️" },
  { name: "Marlène Feedback", title: "Je donne du feedback constructif depuis 2016 · Toujours", emoji: "📝" },
  { name: "Florent 360°", title: "Vision 360° · Action 360° · Tout à 360° · C'est beaucoup", emoji: "🔁" },
  { name: "Annick Reconvertie", title: "Ancienne banquière · Maintenant souffleuse de verre · LinkedIn quand même", emoji: "🦚" },
  { name: "Raphaël No-Drama", title: "Je gère les conflits sans drama. Ça m'a pris 20 ans.", emoji: "🕊️" },
  { name: "Charline Meta", title: "Early adopter · Metaverse consultant · Toujours là", emoji: "🥽" },
  { name: "Lionel Territoire", title: "Développeur de territoires · Je ne sais pas ce que ça veut dire non plus", emoji: "🗺️" },
  { name: "Gwenaëlle RH+", title: "RH augmentée · People first · Organigramme en dernier", emoji: "✊" },
  { name: "Mehdi Product", title: "Head of Product · Roadmap · Backlog · Grooming · Souffrance", emoji: "🧩" },
  { name: "Bastien Frugal", title: "Innovation frugale · Moins c'est plus · Sauf pour le salaire", emoji: "🪨" },
  { name: "Audrey AI-First", title: "AI-first thinker · Tous mes posts écrits par Claude · Shhh", emoji: "🤯" },
  { name: "Pascal Synergies", title: "Créateur de synergies · Si vous voyez une synergie, appelez-moi", emoji: "🔗" },
  { name: "Véronique Transfo", title: "Directrice de la Transformation · La transformation n'est pas finie", emoji: "🦠" },
  { name: "Bob le Stagiaire", title: "Stagiaire · M2 · Disponible · Très disponible · S'il vous plaît", emoji: "🙋" },
  { name: "Christine Bienêtre", title: "Bien-être au travail · Plantes dans l'open-space · Table de ping-pong", emoji: "🪴" },
  { name: "Nicolas Weby", title: "Digital native · Né avec internet · Né en 1975", emoji: "🌐" },
  { name: "Sabine Parole", title: "La parole libère. Je libère des paroles. En formation.", emoji: "🗣️" },
  { name: "Henri Leverage", title: "I leverage things · All the things · Toujours", emoji: "⚖️" },
  { name: "Priya S.", title: "Diversity champion · Inclusive leader · Background check : oui", emoji: "🌏" },
  { name: "Thibaut Sigma", title: "Six Sigma Black Belt · Lean · Kaizen · Ma femme est partie", emoji: "⬛" },
  { name: "Zoé Ex-Startup", title: "Ex-startup · Post-startup · Inter-startups · Startup again ?", emoji: "🎢" },
  { name: "Damien Gratitude", title: "Chaque matin je note 3 gratitudes. Depuis 847 jours.", emoji: "📒" },
  { name: "Jacques-Henri M.", title: "Conseil d'Administration · Jeune retraité actif · Petits-enfants", emoji: "🧣" },
  { name: "Svetlana B.", title: "Franco-russe · Trilingual · Interculturel · Compliqué en ce moment", emoji: "🌷" },
  { name: "Pierrick Synapse", title: "Neurosciences appliquées au management · Le cerveau c'est fascinant", emoji: "🧬" },
  { name: "Magalie Slow", title: "Slow management · Slow food · Slow LinkedIn · Post tous les 3 mois", emoji: "🐢" },
  { name: "Gontran F.", title: "Héritier · Business angel · Passionné de chevaux et de ROI", emoji: "🎠" },
  { name: "Cindy Influence", title: "Content creator B2B · Collab welcome · Tarifs en DM", emoji: "💅" },
  { name: "Rémi sans H", title: "On a supprimé le H. On a gardé l'ambition.", emoji: "🤷" },
  { name: "Dominique (H ou F)", title: "CSO · Parfois CTO · Ça dépend des semaines", emoji: "🌀" },
  { name: "Armand Networking", title: "Je connais 4800 personnes · Dont certaines en vrai", emoji: "🕸️" },
  { name: "Laurence 2.0", title: "Je me suis mise à jour en 2022 · Patch encore en cours", emoji: "🖨️" },
  { name: "Théo Ex-HEC", title: "HEC 2019 · J'en parle encore · Je suis pardonnable", emoji: "🎓" },
  { name: "Séverine B.", title: "Revenue Operations · Ops tout court · Tout ce que personne ne veut faire", emoji: "🔦" },
  { name: "Jérémy Side-Project", title: "Salarié le jour · Fondateur la nuit · Épuisé en permanence 🚀", emoji: "🛸" },
  { name: "Monique Digitale", title: "55 ans · Je m'y suis mise · LinkedIn depuis 2021 · Fière", emoji: "💾" },
  { name: "Xavier Le Pionnier", title: "J'étais là avant que ce soit mainstream · Toujours", emoji: "🧭" },
  { name: "Elodie Sens", title: "En quête de sens · Le sens est quelque part · Je cherche encore", emoji: "🕯️" },
  { name: "Fernand Agile", title: "Certified Scrum Master · Certified SAFe · Certified fatigué", emoji: "🧶" },
  { name: "Wendeline K.", title: "Chief of Staff · Je fais ce que le CEO oublie de faire", emoji: "🦜" },
  { name: "Patrice Intrapreneur", title: "Intrapreneur depuis 17 ans · Dans la même entreprise · Oui", emoji: "🏗️" },
  { name: "Cassandre V.", title: "J'avais prédit tout ça. Personne ne m'a écoutée. Comme d'hab.", emoji: "🔮" },
] as const;

export const VALID_SKILLS = [
  "Pensée Disruptive",
  "Synergies",
  "Excel (VLOOKUP)",
  "Leadership Bienveillant",
  "Réunions debout",
  "Agilité Mentale",
  "Storytelling Authentique",
  "Réseautage Stratégique",
  "Growth Hacking",
  "Management par la Confiance",
  "Transformation Digitale",
  "Mindset de Croissance",
  "Personal Branding",
  "Gestion du Changement",
  "Communication Non Violente",
  "Pivot Stratégique",
  "PowerPoint Avancé",
  "Résilience",
  "Vision Holistique",
  "Coworking",
  "Ikigai",
  "KPI",
  "OKR",
  "Design Thinking",
  "Écoute Active",
  "Délégation",
  "SEO (bases)",
  "Excel (tableaux croisés)",
  "Canva",
  "Calendly",
  "Notion",
  "Slack (pro)",
  "Faire des réunions sur les réunions",
  "Resilience (orthographe variable)",
  "ChatGPT (utilisateur avancé)",
  "Miro (les post-its)",
  "Dire non avec bienveillance",
  "Asana (colonne 'À faire')",
  "Présentiel hybride",
  "Feedback sandwich",
  "Pensée systémique",
  "Curiosité insatiable",
  "Vision 360°",
  "Co-construction",
  "Intelligence émotionnelle",
  "Facilitation (avoir un marqueur)",
  "Ownership",
  "Deep work (2h max)",
  "Networking (LinkedIn uniquement)",
  "Excel (filtre automatique)",
  "Zoom (partage d'écran)",
  "Faire semblant d'être occupé",
  "Dire 'on va aligner les planètes'",
  "Trouver des quick wins",
  "Mettre du 'humain' dans tout",
  "Inventer des acronymes",
  "Relancer sans relancer",
  "Changer de job tous les 18 mois",
  "Écrire 'je' avec une minuscule",
  "Mettre 🙏 à la fin de chaque phrase",
  "S'auto-proclamer expert",
  "Organiser des ateliers sans livrables",
  "Parler en 'on' pour éviter les responsabilités",
  "Transformation par la marche",
  "Réunion debout (mais on s'est assis après 3 min)",
  "ChatGPT prompt engineering",
  "Savoir dire non (en formation)",
  "Bullet journaling professionnel",
  "Détox numérique partielle",
  "Leadership situationnel (la théorie)",
  "Feedback positif systématique",
  "Couper la caméra en visio",
  "Remettre au lendemain avec intention",
  "Automatisation (IFTTT)",
  "Méditation corporate (7 min max)",
  "Dire 'fail fast' sans avoir raté",
  "Construire des ponts (métaphoriques)",
  "Storytelling de la reconversion",
  "Trouver son why (Simon Sinek)",
  "Excel (SUMIF)",
  "Dire 'ça fait sens' sans sourciller",
  "Proposer un call de 15 min qui dure 1h",
  "Envoyer des vocaux WhatsApp de 8 min",
  "Mettre 'je' en minuscule pour paraître humble",
  "Commencer chaque post par une question rhétorique",
  "Terminer chaque post par 'Et vous ?'",
  "Promettre un thread qui n'arrive jamais",
  "LinkedIn Learning (certificat en 2h)",
  "Inviter des inconnus sans message",
  "Répondre à 3 semaines de retard en disant 'je reviens de vacances'",
  "Écrire 'je partage car ça m'a beaucoup touché'",
  "Se souvenir du prénom de tout le monde (CRM mental)",
  "Inbound marketing organique naturel",
  "Travailler en mode projet (pas de projet précis)",
  "Penser en dehors du cadre (sans sortir du bureau)",
  "Pivoter (avoir changé d'avis une fois)",
  "Être son propre chef (chômage entrepreneurial)",
  "Dire 'on est sur la même longueur d'onde' à des inconnus",
  "Newsletter mensuelle (2 éditions publiées)",
  "Trouver des opportunités dans les crises",
  "Management par le sens commun",
  "Podcast (3 épisodes, dernier en 2022)",
] as const;

export const BOT_COMMENTS = [
  "Merci pour ce partage inspirant ! 🙏",
  "Tellement vrai. J'ai vécu exactement la même chose.",
  "Je partage entièrement cette vision disruptive.",
  "Ça donne à réfléchir. Bravo pour le courage de le dire.",
  "Excellent contenu ! Je le partage avec mon réseau de 3 personnes.",
  "C'est exactement ce dont le monde professionnel a besoin.",
  "J'ai quitté mon CDI pour ça. Pas de regrets. 🚀",
  "Powerful. Just powerful.",
  "Vous avez résumé ce que je ressens depuis 5 ans en 3 lignes. Merci.",
  "+1 👆",
  "Le monde a besoin de plus de contenus comme celui-ci.",
  "Je valide à 100%. Mon coach m'a dit la même chose.",
  "Humilié ET inspiré. Merci.",
  "Post épinglé dans mon bureau. 📌",
  "Je vais en parler à mon équipe dès lundi.",
  "Ceci devrait être enseigné dans toutes les écoles de commerce.",
  "Chills. Littéralement des frissons.",
  "On ne le dit pas assez. Merci de le dire.",
  "Bookmarké, screenshoté, imprimé.",
  "Vous venez de débloquer quelque chose en moi.",
  "Mon CEO doit lire ça. Je lui transfère maintenant.",
  "3 fois que je relis ce post. Chaque fois je trouve quelque chose de nouveau.",
  "C'est un peu ma vie que vous décrivez là.",
  "Je n'avais pas les mots. Vous les avez trouvés.",
  "Ça mérite une standing ovation numérique. 👏👏👏",
  "J'ai partagé ça à ma mère. Elle a pleuré.",
  "Sage. Tout simplement sage.",
  "En 2 ans de LinkedIn je n'avais jamais commenté. Là je ne pouvais pas ne pas le faire.",
  "Ce post va vieillir comme du bon vin.",
  "Sauvegarder pour relire dans les moments difficiles.",
  "On devrait imprimer ça dans les open-spaces.",
  "Voilà pourquoi je viens sur LinkedIn. Merci.",
  "J'ai lu ça à mon équipe en réunion de lancement. Silence total. Puis applaudissements.",
  "Paragraphe 3, phrase 2. Tatoué dans ma mémoire.",
  "Ce contenu est gratuit ? C'est illégal.",
  "Vous facturez des formations ? Je demande pour un ami (moi).",
  "Directement dans ma newsletter. Crédit bien sûr. 🙏",
  "Tag ton ami qui a besoin de lire ça. (j'en ai tagué 14)",
  "Vous avez 10 fois plus de valeur que la moitié des keynotes à 3000€.",
  "Ma retraite spirituelle à Bali m'a appris la même chose.",
  "Je vis cette situation EN CE MOMENT MÊME en vous lisant.",
  "Humble mais impactant. Rare.",
  "Je mets en pratique dès ce soir. Update dans 30 jours. 💪",
  "C'est drôle parce que mon thérapeute m'a dit exactement pareil.",
  "Vous êtes le Simon Sinek français que l'on mérite.",
  "Flagué pour mes enfants. Ils sont en CE1 mais ça attendra.",
  "Double tap si tu lis ça à 23h en pyjama en te demandant où ta carrière s'en va.",
  "Je reviens dans 6 mois vous dire où j'en suis. (spoiler: bien.)",
  "Votre personal brand est INCROYABLE. Ça se voit.",
  "On n'en parle pas assez dans les Comex. Bien joué.",
  "Je viens de quitter une réunion pour lire ce post jusqu'au bout. Aucun regret.",
  "Ce post a guéri quelque chose en moi que je ne savais pas cassé.",
  "Mon mari a demandé pourquoi je pleurais. Je lui ai lu le post. Il pleure aussi maintenant.",
  "J'ai mis ça en fond d'écran. Mon fond d'écran c'était mes enfants avant.",
  "Vous êtes en train de pitcher quoi ? Je sors mon chéquier.",
  "C'est quoi votre Myers-Briggs ? Je sens qu'on est pareils.",
  "Partagé en interne. Le CODIR a demandé une présentation. Merci.",
  "Mon ChatGPT ne produit jamais quelque chose d'aussi profond.",
  "Lu, relu, médité, pratiqué. Résultats dans 3 à 5 ans business days.",
  "Voilà ce que j'essaie d'expliquer depuis des années à mes associés. Merci de le dire mieux que moi.",
  "J'ai failli scroller. Et puis j'ai lu la première ligne. Et ma vie a changé.",
  "Vous venez de décrire mon lundi matin avec une précision chirurgicale.",
  "Incroyable. Et en plus c'est gratuit sur LinkedIn ? Le monde est fou.",
  "Je candidate spontanément dans votre vie professionnelle. CV dispo.",
  "Post of the year. Année pas encore finie mais le titre est attribué.",
  "J'ai mis en pratique il y a 10 minutes. Déjà des résultats. Pas de kidding.",
  "C'est exactement pour ça que j'ai désactivé TikTok. Merci LinkedIn.",
  "Vous devriez avoir 2 millions d'abonnés. C'est une honte que vous n'en ayez que 3.",
  "Je connais quelqu'un qui devrait lire ça. Moi. Je parle de moi.",
  "Lu à voix haute à mon chien. Il a hoché la tête. Sérieusement.",
  "Ce post contient plus de valeur que mon MBA. Et j'ai payé 40k pour le MBA.",
  "Commentaire rapide avant de partir en retraite de silence numérique. Ça valait la peine.",
  "Vous êtes dans ma liste des 3 personnes qui m'ont changé. Les 2 autres sont Mandela et mon boucher.",
  "Algorithme, mets ce post devant TOUT LE MONDE.",
  "Je relis ça chaque matin depuis 3 jours. C'est mon nouveau rituel.",
  "Vous avez décrit en 5 lignes ce que Brené Brown met 300 pages à expliquer.",
  "J'ai annoté ce post comme si c'était ma thèse. Merci pour l'insight.",
  "Je suis en vacances mais j'ai quand même lu ça. Ça dit tout.",
  "Mon fils de 11 ans a lu par-dessus mon épaule. Il a demandé à faire du business.",
  "Vous décrivez en 8 lignes ce que j'ai mis 15 ans à comprendre. Pas jaloux. Si un peu.",
  "Screenshottté et envoyé à 7 personnes. Dont mon ex. Pour qu'il comprenne enfin.",
  "Ce n'est pas un post. C'est une thérapie de groupe à ciel ouvert.",
  "Je suis arrivé ici depuis une pub pour des chaussures. La vie est bien faite.",
  "Impressionnant. Et vous avez l'air sympa en plus. Double menace.",
  "J'ai failli ne pas lire la suite après le deuxième paragraphe. Erreur que j'aurais regrettée toute ma vie.",
  "Votre profil dit que vous êtes à Paris. Je suis aussi à Paris. Coïncidence ? Je ne pense pas.",
  "Vous auriez dû être prof. Vos anciens élèves ne savent pas ce qu'ils ont raté.",
  "Post lu à 6h34 du matin. Premier café pas encore bu. Déjà impacté.",
  "Je travaille dans le même secteur depuis 12 ans et je n'avais JAMAIS formulé ça ainsi.",
  "C'est exactement l'opposé de ce qu'on m'a appris à l'école. Enfin quelqu'un qui dit la vérité.",
  "Je ne sais pas qui vous êtes mais je vous fais confiance à 100%.",
  "Quelqu'un devrait faire une série Netflix basée sur ce post.",
  "J'ai relu 3 fois le dernier paragraphe. J'ai eu un déclic. Puis un autre déclic. Puis un troisième.",
  "Dans 10 ans on citera ce post dans des livres de management.",
  "Vous parlez de moi sans me connaître. C'est troublant. C'est beau.",
  "J'avais prévu de poster quelque chose aujourd'hui. Je reporte. Ça mérite mieux après ça.",
  "Moins de 200 mots. Plus d'impact que mon dernier séminaire de 2 jours.",
  "Le like ne suffit pas. Le commentaire ne suffit pas. Je partage et je prie.",
  "Envoyé à mon manager. Il a mis 8 minutes à répondre 'oui'. Record.",
  "Vous venez de valider une décision que je n'avais pas encore prise. Merci.",
  "J'ai 847 connexions. Je ne commente jamais. Là si. Ça compte.",
  "Votre authenticité est désarmante. Restez comme ça. Le monde en a besoin.",
  "Je lis ça dans les transports et les gens me regardent parce que je hoche la tête tout seul.",
  "Posté depuis 2h. Déjà 4 likes. L'algorithme dort. Nous non.",
  "C'est drôle, j'écrivais un post sur exactement ce sujet. Je l'efface. Le vôtre est meilleur.",
  "Vu, lu, ressenti, intégré. Je vais méditer là-dessus ce soir.",
  "Top 3 des posts de ma carrière LinkedIn. Les 2 autres étaient de vous aussi.",
  "Vous avez le courage de dire ce que tout le monde pense tout bas. Héros.",
  "Premier post que je lis depuis que j'ai mis LinkedIn en pause pour ma santé mentale. Bon retour.",
  "Je ne suis pas sûr de tout comprendre mais je suis sûr que c'est important.",
  "Je vais faire semblant que ce post n'existe pas pour ne pas avoir à changer.",
  "Mon père dit la même chose depuis 30 ans mais lui ça l'a rendu aigri. Vous ça rend inspirant.",
  "J'ai lu ça entre deux bouchées de sandwich. Tragique et magique à la fois.",
  "Ce post m'a convaincu de postuler à un job que je ne mérite pas encore. On verra.",
  "J'ai failli éteindre mon téléphone pour de vrai cette fois. Et puis ce post.",
  "La première phrase m'a arrêtée net. J'attendais le bus depuis 20 minutes. Je l'ai raté. Aucun regret.",
  "Vous avez 312 likes. C'est une insulte. Ce post mérite la paix mondiale.",
  "Mon chéri m'a demandé pourquoi je souriais toute seule. Compliqué à expliquer.",
  "J'aurais voulu écrire ça. Mais je suis comptable. Alors merci d'exister.",
  "Ça résonne tellement que j'ai cru avoir un problème de connexion.",
  "J'ai copié-collé ça dans mon journal intime. Première entrée depuis 2019.",
  "Vous avez le QI d'Einstein et le cœur de Mère Teresa. La combinaison parfaite.",
  "Je suis venu sur LinkedIn pour stalker un ex. Je repars transformé.",
  "Mon manager doit lire ça. Sauf que si il le lit il va s'y reconnaître.",
  "J'ai relu la phrase centrale 9 fois. À la 9e j'avais les larmes aux yeux. 9 c'est beaucoup.",
  "Vous avez dit en 4 minutes de lecture ce que je n'arrive pas à dire en 4 ans de thérapie.",
  "Quelqu'un devrait vous payer juste pour exister sur LinkedIn.",
  "J'hésite à partager tellement j'ai envie de le garder pour moi.",
  "J'ai envoyé ça à ma RH. Elle a mis 'j'adore'. Je suis toujours en attente de ma promo.",
  "Stop. Je pose tout. Je lis ce post entier. Debout. Comme au théâtre.",
  "C'est la 4e fois que je like ce post. LinkedIn en retire un à chaque fois. Algorithme jaloux.",
  "Je n'avais pas prévu de commenter. Mais ma conscience professionnelle m'en voulait si je ne le faisais pas.",
  "Vous auriez pu faire payer pour ce contenu. Vous êtes un saint.",
  "Posté à 7h23. Lu à 7h24. Je guettais. Je ne suis pas normal.",
  "Lu pendant une réunion. Je n'ai rien raté d'important. La réunion, pas le post.",
  "Ce post devrait être obligatoire dans les parcours d'intégration. Je le soumets à mon DRH ce soir.",
  "Votre authenticité m'a donné la permission d'être moi-même pendant 3 minutes. Merci.",
  "J'ai taggé 6 personnes puis supprimé les tags. Trop précieux pour être partagé.",
] as const;

export const BOT_REPLIES = [
  "Tellement d'accord avec vous !",
  "Merci pour ce commentaire qui résonne.",
  "+1 complètement",
  "Voilà quelqu'un qui a compris.",
  "Je vais partager ça à mon réseau.",
  "Vous avez tout compris. 🙏",
  "Ce genre d'échanges me rappelle pourquoi je reste sur LinkedIn.",
  "On devrait prendre un café virtuel pour approfondir ça.",
  "Je sens qu'on a la même vision des choses.",
  "Vous mettez le doigt exactement là où ça fait.",
  "Merci du fond du cœur pour cet éclairage.",
  "J'allais écrire exactement la même chose.",
  "Voilà quelqu'un avec qui j'aurais aimé travailler plus tôt.",
  "DM envoyé. On a des choses à se dire.",
  "Vous avez transformé mon commentaire en réflexion profonde.",
  "C'est pour ça que je vous follow depuis le début.",
  "Vous venez de résumer 6 mois de thérapie en une phrase.",
  "J'ai relu votre commentaire 4 fois. Chaque fois c'est mieux.",
  "On n'est pas prêts pour cette conversation. Mais on en a besoin.",
  "Je notifie mon associé. Il a besoin d'entendre ça de quelqu'un d'autre que moi.",
  "Exactement. Mot pour mot ce que je pensais sans savoir le dire.",
  "Vous avez le don de transformer les évidences en révélations. Rare.",
  "Première fois que je réponds à un commentaire en 4 ans. Vous le méritez.",
  "Connecté immédiatement. Je ne fais jamais ça. Sauf là.",
  "C'est ça la valeur ajoutée de LinkedIn. Vous, ici, ce soir.",
  "Je mets +1 mais dans mon cœur c'est +1000.",
  "Vous avez une newsletter ? Non ? C'est un crime.",
  "Votre commentaire m'a donné matière à un prochain post. Crédit partagé.",
  "On devrait absolument se croiser à un événement networking un jour.",
  "Je sens que vous comprenez des choses que la plupart ignorent.",
  "Ce que vous dites là mérite sa propre publication.",
  "Rare de voir quelqu'un apporter autant de valeur dans un commentaire.",
  "Je vous ai ajouté à ma liste de personnes à suivre de très près.",
  "Votre intervention élève toute la conversation. Merci.",
  "Vous avez résumé en 2 phrases ce que je développe en 30 min en keynote.",
  "Je n'aurais pas dit mieux. Littéralement, j'ai essayé. J'ai pas pu.",
  "Ce commentaire vaut un post à lui tout seul.",
  "Toujours aussi pertinent. C'est votre marque de fabrique.",
  "On est visiblement alignés sur l'essentiel. C'est rassurant.",
  "Je vais me permettre de vous citer lors de mon prochain atelier.",
  "Exactement ce que j'aurais voulu dire si j'avais eu vos mots.",
  "Ce genre de commentaire me rappelle pourquoi je publie encore.",
  "Vous posez le doigt sur quelque chose que même moi je n'avais pas conscientisé.",
  "Vous avez une façon de reformuler qui rend tout limpide. Don rare.",
  "Je réponds rarement aux commentaires. Là je ne pouvais pas ne pas le faire.",
  "Franchement : vous devriez écrire un livre. Je l'achète d'avance.",
  "Votre commentaire m'a fait rater mon arrêt de métro. Beau dommage.",
  "C'est ça qu'on appelle l'intelligence collective. On vient de la créer ensemble.",
  "Je ne réponds jamais aux commentaires en semaine. Exception accordée.",
  "Vous portez ce sujet avec une élégance que peu de gens ont.",
  "Vous venez de co-écrire la suite de ce post sans le savoir.",
  "Ce que vous dites là devrait être un post à part entière. Je vous le suggère formellement.",
  "Votre commentaire vaut plus que 90% des posts que j'ai publiés. Humiliant. Merci.",
  "Je sens qu'on aurait pu s'associer dans une autre vie.",
  "Vous avez mis en mots ce que je ressens le dimanche soir depuis 12 ans.",
  "Le like est trop petit. Il faudrait un bouton 'vie changée'.",
  "Quelqu'un de brillant qui prend le temps de commenter. Ça n'a pas de prix.",
  "Je vous ai cherché sur LinkedIn pour vous ajouter. Vous êtes déjà dans mon réseau. L'univers sait.",
  "Voilà le commentaire qui donne envie d'écrire encore. Vraiment.",
  "Si un jour vous montez une formation, je m'inscris sur liste d'attente maintenant.",
  "J'aurais voulu vous répondre plus tôt mais j'avais besoin de digérer.",
  "Merci d'être là. Pas juste ici. En général.",
  "Ce fil de commentaires est meilleur que la plupart des conférences que j'ai payées.",
  "Deux inconnus sur internet qui font avancer la pensée managériale. C'est beau.",
  "Je vais dormir sur cette réponse et revenir demain avec quelque chose de digne.",
] as const;

export const REACTION_ICONS: Record<string, string> = {
  Inspirant: "💡",
  Bravo: "👏",
  Fascinant: "🤩",
  Instructif: "📚",
  Drôle: "😄",
  Soutien: "🫂",
};

export const VALID_REACTIONS = ["Inspirant", "Bravo", "Fascinant", "Instructif", "Drôle", "Soutien"] as const;
export type Reaction = typeof VALID_REACTIONS[number];

// Timing constants
export const MIN_BOT_POST_INTERVAL_MS = 3 * 60 * 1000;
export const BOT_VIEW_INTERVAL_MS = 60 * 60 * 1000;
export const PROFILE_VIEW_DEDUP_MS = 24 * 60 * 60 * 1000;
export const MAX_POSTS_LIMIT = 50;
