export type ThemeId = "win95" | "dark" | "vaporwave" | "hacker";

export interface Theme {
  id: ThemeId;
  name: string;
  emoji: string;
  description: string;
  vars: Record<string, string>;
}

export const THEMES: Theme[] = [
  {
    id: "win95",
    name: "Windows 95",
    emoji: "🖥️",
    description: "Le classique intemporel",
    vars: {
      "--t-bg": "#c0c0c0",
      "--t-bg-light": "#ffffff",
      "--t-bg-dark": "#808080",
      "--t-bg-darker": "#404040",
      "--t-border-light": "#ffffff",
      "--t-border-dark": "#808080",
      "--t-titlebar-from": "#000080",
      "--t-titlebar-to": "#1084d0",
      "--t-titlebar-text": "#ffffff",
      "--t-accent": "#000080",
      "--t-accent-hover": "#0000a0",
      "--t-text": "#000000",
      "--t-text-muted": "#444444",
      "--t-text-subtle": "#808080",
      "--t-marquee-bg": "#000000",
      "--t-marquee-text": "#00ff00",
      "--t-card-bg": "#ffffff",
      "--t-card-hover": "#ffffcc",
      "--t-card-hover-border": "#ffaa00",
      "--t-page-from": "#b8d8f0",
      "--t-page-to": "#87b8d8",
      "--t-badge-bg": "#cc0000",
      "--t-badge-text": "#ffff00",
      "--t-inset-from": "#e8f4fd",
      "--t-inset-to": "#c6e2f5",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
    },
  },
  {
    id: "dark",
    name: "Nuit profonde",
    emoji: "🌙",
    description: "Mode sombre élégant",
    vars: {
      "--t-bg": "#1a1a2e",
      "--t-bg-light": "#16213e",
      "--t-bg-dark": "#0f0f23",
      "--t-bg-darker": "#080818",
      "--t-border-light": "#2a2a5e",
      "--t-border-dark": "#0d0d30",
      "--t-titlebar-from": "#0d0d30",
      "--t-titlebar-to": "#1a1a6e",
      "--t-titlebar-text": "#a0c4ff",
      "--t-accent": "#4f8ef7",
      "--t-accent-hover": "#7aaeff",
      "--t-text": "#e0e0ff",
      "--t-text-muted": "#9090bb",
      "--t-text-subtle": "#5050aa",
      "--t-marquee-bg": "#0d0d30",
      "--t-marquee-text": "#4f8ef7",
      "--t-card-bg": "#16213e",
      "--t-card-hover": "#1e2d5a",
      "--t-card-hover-border": "#4f8ef7",
      "--t-page-from": "#080818",
      "--t-page-to": "#0d0d30",
      "--t-badge-bg": "#4f8ef7",
      "--t-badge-text": "#ffffff",
      "--t-inset-from": "#0d0d30",
      "--t-inset-to": "#16213e",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
    },
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    emoji: "🌸",
    description: "A E S T H E T I C",
    vars: {
      "--t-bg": "#2d1b69",
      "--t-bg-light": "#3d2480",
      "--t-bg-dark": "#1a0f40",
      "--t-bg-darker": "#0d0820",
      "--t-border-light": "#ff71ce",
      "--t-border-dark": "#b967ff",
      "--t-titlebar-from": "#b967ff",
      "--t-titlebar-to": "#ff71ce",
      "--t-titlebar-text": "#ffffff",
      "--t-accent": "#01cdfe",
      "--t-accent-hover": "#fffb96",
      "--t-text": "#fffb96",
      "--t-text-muted": "#ff71ce",
      "--t-text-subtle": "#b967ff",
      "--t-marquee-bg": "#0d0820",
      "--t-marquee-text": "#01cdfe",
      "--t-card-bg": "#3d2480",
      "--t-card-hover": "#4d2f9f",
      "--t-card-hover-border": "#01cdfe",
      "--t-page-from": "#0d0820",
      "--t-page-to": "#1a0f40",
      "--t-badge-bg": "#ff71ce",
      "--t-badge-text": "#0d0820",
      "--t-inset-from": "#1a0f40",
      "--t-inset-to": "#2d1b69",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
    },
  },
  {
    id: "hacker",
    name: "Hacker",
    emoji: "💀",
    description: "We are in",
    vars: {
      "--t-bg": "#0a0a0a",
      "--t-bg-light": "#111111",
      "--t-bg-dark": "#050505",
      "--t-bg-darker": "#000000",
      "--t-border-light": "#00ff41",
      "--t-border-dark": "#004d14",
      "--t-titlebar-from": "#001500",
      "--t-titlebar-to": "#003000",
      "--t-titlebar-text": "#00ff41",
      "--t-accent": "#00ff41",
      "--t-accent-hover": "#00ff80",
      "--t-text": "#00ff41",
      "--t-text-muted": "#00aa2b",
      "--t-text-subtle": "#005514",
      "--t-marquee-bg": "#000000",
      "--t-marquee-text": "#00ff41",
      "--t-card-bg": "#0d0d0d",
      "--t-card-hover": "#001500",
      "--t-card-hover-border": "#00ff41",
      "--t-page-from": "#000000",
      "--t-page-to": "#000500",
      "--t-badge-bg": "#00ff41",
      "--t-badge-text": "#000000",
      "--t-inset-from": "#001500",
      "--t-inset-to": "#000800",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-vt323)",
    },
  },
];

export const DEFAULT_THEME_ID: ThemeId = "win95";
