export type ThemeId = "win95" | "winxp" | "winvista" | "win7" | "dark" | "vaporwave" | "hacker" | "amber" | "sunset";

/**
 * Nouvelles variables visuelles ajoutées aux vars de base :
 *
 * --t-window-radius    : border-radius des fenêtres/menus (0px pour 95/XP, ~6px pour Vista/7)
 * --t-window-shadow    : box-shadow des fenêtres (solide offset pour 95, diffus pour Vista/7)
 * --t-dialog-shadow    : box-shadow des dialogs (plus prononcé que les fenêtres)
 * --t-taskbar-bg       : fond de la taskbar (peut être différent de --t-bg, ex: verre pour Vista/7)
 * --t-taskbar-blur     : backdrop-filter blur de la taskbar (0 pour 95/XP, blur pour Vista/7)
 * --t-glass-bg         : fond semi-transparent des fenêtres Aero (rgba)
 * --t-glass-blur       : backdrop-filter blur des fenêtres Aero
 * --t-glass-border     : bordure teintée Aero
 * --t-titlebar-radius  : border-radius de la titlebar seule
 * --t-scanlines        : opacité des scanlines CRT (0 = désactivé)
 * --t-start-btn-bg     : fond spécial bouton Démarrer (ex: gradient vert XP)
 * --t-start-btn-text   : texte bouton Démarrer
 */

export interface Theme {
  id: ThemeId;
  name: string;
  emoji: string;
  description: string;
  /** Palette rapide pour la preview dans le sélecteur de thème */
  preview: {
    bg: string;
    titlebarFrom: string;
    titlebarTo: string;
    titlebarText: string;
    accent: string;
    text: string;
  };
  vars: Record<string, string>;
}

export const THEMES: Theme[] = [
  {
    id: "win95",
    name: "Windows 95",
    emoji: "🖥️",
    description: "Le classique intemporel",
    preview: {
      bg: "#c0c0c0",
      titlebarFrom: "#000080",
      titlebarTo: "#1084d0",
      titlebarText: "#ffffff",
      accent: "#000080",
      text: "#000000",
    },
    vars: {
      "--t-bg": "#c0c0c0",
      "--t-bg-light": "#ffffff",
      "--t-bg-dark": "#a0a0a0",
      "--t-bg-darker": "#808080",
      "--t-border-light": "#ffffff",
      "--t-border-dark": "#808080",
      "--t-titlebar-from": "#000080",
      "--t-titlebar-to": "#1084d0",
      "--t-titlebar-text": "#ffffff",
      "--t-accent": "#000080",
      "--t-accent-hover": "#0000c8",
      "--t-text": "#000000",
      "--t-text-muted": "#444444",
      "--t-text-subtle": "#808080",
      "--t-marquee-bg": "#000000",
      "--t-marquee-text": "#00ff00",
      "--t-card-bg": "#d8d8d8",
      "--t-card-hover": "#ffffcc",
      "--t-card-hover-border": "#ffaa00",
      "--t-page-from": "#b8d8f0",
      "--t-page-to": "#87b8d8",
      "--t-badge-bg": "#cc0000",
      "--t-badge-text": "#ffff00",
      "--t-inset-from": "#e8e8e8",
      "--t-inset-to": "#d0d0d0",
      "--t-app-bg": "#ffffff",
      "--t-app-text": "#000000",
      "--t-app-text-muted": "#444444",
      "--t-progress-from": "#000080",
      "--t-progress-to": "#1084d0",
      "--t-defrag-used": "#000080",
      "--t-defrag-fragmented": "#cc0000",
      "--t-defrag-free": "#ffffff",
      "--t-defrag-system": "#808080",
      "--t-defrag-mystery": "#ffaa00",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "0px",
      "--t-titlebar-radius": "0px",
      "--t-window-shadow": "4px 4px 0 rgba(0,0,0,0.5)",
      "--t-dialog-shadow": "6px 6px 0 rgba(0,0,0,0.5)",
      "--t-taskbar-bg": "#c0c0c0",
      "--t-taskbar-blur": "none",
      "--t-glass-bg": "#c0c0c0",
      "--t-glass-blur": "none",
      "--t-glass-border": "#c0c0c0",
      "--t-scanlines": "0.12",
      "--t-start-btn-bg": "linear-gradient(to bottom, var(--t-bg-light), var(--t-bg))",
      "--t-start-btn-text": "#000000",
    },
  },
  {
    id: "winxp",
    name: "Windows XP",
    emoji: "🟩",
    description: "Bliss & Luna style",
    preview: {
      bg: "#245edb",
      titlebarFrom: "#2275d7",
      titlebarTo: "#5ba8e5",
      titlebarText: "#ffffff",
      accent: "#ff8c00",
      text: "#ffffff",
    },
    vars: {
      "--t-bg": "#245edb",
      "--t-bg-light": "#3a7fd4",
      "--t-bg-dark": "#1a4ab8",
      "--t-bg-darker": "#0f3090",
      "--t-border-light": "#7ab8f5",
      "--t-border-dark": "#1a4ab8",
      "--t-titlebar-from": "#2275d7",
      "--t-titlebar-to": "#5ba8e5",
      "--t-titlebar-text": "#ffffff",
      "--t-accent": "#ff8c00",
      "--t-accent-hover": "#ffaa33",
      "--t-text": "#ffffff",
      "--t-text-muted": "#cce0ff",
      "--t-text-subtle": "#88b8f0",
      "--t-marquee-bg": "#0f3090",
      "--t-marquee-text": "#ffdd00",
      "--t-card-bg": "#d9ecff",
      "--t-card-hover": "#eef6ff",
      "--t-card-hover-border": "#ff8c00",
      "--t-page-from": "#2277cc",
      "--t-page-to": "#55aaee",
      "--t-badge-bg": "#ff8c00",
      "--t-badge-text": "#ffffff",
      "--t-inset-from": "#1a4ab8",
      "--t-inset-to": "#2a6ad8",
      "--t-app-bg": "#ece9d8",
      "--t-app-text": "#000000",
      "--t-app-text-muted": "#444444",
      "--t-progress-from": "#2275d7",
      "--t-progress-to": "#5ba8e5",
      "--t-defrag-used": "#245edb",
      "--t-defrag-fragmented": "#cc3300",
      "--t-defrag-free": "#ece9d8",
      "--t-defrag-system": "#888888",
      "--t-defrag-mystery": "#ff8c00",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "0px",
      "--t-titlebar-radius": "0px",
      "--t-window-shadow": "3px 3px 8px rgba(0,0,0,0.4)",
      "--t-dialog-shadow": "5px 5px 12px rgba(0,0,0,0.45)",
      "--t-taskbar-bg": "#1e4a9a",
      "--t-taskbar-blur": "none",
      "--t-glass-bg": "#245edb",
      "--t-glass-blur": "none",
      "--t-glass-border": "#245edb",
      "--t-scanlines": "0",
      "--t-start-btn-bg": "linear-gradient(to bottom, #3ca836 0%, #52c242 40%, #2a8c1e 60%, #3ca836 100%)",
      "--t-start-btn-text": "#ffffff",
    },
  },
  {
    id: "winvista",
    name: "Windows Vista",
    emoji: "💎",
    description: "Aero Glass & Transparence",
    preview: {
      bg: "#1c3a5c",
      titlebarFrom: "#3a7bba",
      titlebarTo: "#a8d4f5",
      titlebarText: "#ffffff",
      accent: "#4db8ff",
      text: "#e8f4ff",
    },
    vars: {
      "--t-bg": "#1c3a5c",
      "--t-bg-light": "#2a5080",
      "--t-bg-dark": "#112540",
      "--t-bg-darker": "#081528",
      "--t-border-light": "#6ab0e8",
      "--t-border-dark": "#1a4070",
      "--t-titlebar-from": "#3a7bba",
      "--t-titlebar-to": "#a8d4f5",
      "--t-titlebar-text": "#ffffff",
      "--t-accent": "#4db8ff",
      "--t-accent-hover": "#7dd0ff",
      "--t-text": "#e8f4ff",
      "--t-text-muted": "#9cc8ee",
      "--t-text-subtle": "#5090c0",
      "--t-marquee-bg": "#081528",
      "--t-marquee-text": "#4db8ff",
      "--t-card-bg": "#1e4570",
      "--t-card-hover": "#2a5c8a",
      "--t-card-hover-border": "#4db8ff",
      "--t-page-from": "#0d2040",
      "--t-page-to": "#1c3a5c",
      "--t-badge-bg": "#4db8ff",
      "--t-badge-text": "#001428",
      "--t-inset-from": "#0d2040",
      "--t-inset-to": "#1a3a60",
      "--t-app-bg": "#e8f0f8",
      "--t-app-text": "#1a2a40",
      "--t-app-text-muted": "#4a6080",
      "--t-progress-from": "#3a7bba",
      "--t-progress-to": "#a8d4f5",
      "--t-defrag-used": "#3a7bba",
      "--t-defrag-fragmented": "#c04040",
      "--t-defrag-free": "#e8f0f8",
      "--t-defrag-system": "#6090b0",
      "--t-defrag-mystery": "#80d0ff",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "8px",
      "--t-titlebar-radius": "8px",
      "--t-window-shadow": "0 8px 32px rgba(0,0,0,0.55), 0 2px 8px rgba(0,0,0,0.4)",
      "--t-dialog-shadow": "0 12px 40px rgba(0,0,0,0.6)",
      "--t-taskbar-bg": "rgba(30,60,100,0.75)",
      "--t-taskbar-blur": "blur(16px)",
      "--t-glass-bg": "rgba(140,190,240,0.18)",
      "--t-glass-blur": "blur(12px)",
      "--t-glass-border": "rgba(180,220,255,0.4)",
      "--t-scanlines": "0",
      "--t-start-btn-bg": "radial-gradient(ellipse at 50% 60%, #60b8f8 0%, #2060c0 60%, #1040a0 100%)",
      "--t-start-btn-text": "#ffffff",
    },
  },
  {
    id: "win7",
    name: "Windows 7",
    emoji: "🪟",
    description: "Aero Peak, le sommet",
    preview: {
      bg: "#1a2a3a",
      titlebarFrom: "#2a4a6a",
      titlebarTo: "#4a8ab8",
      titlebarText: "#ffffff",
      accent: "#1e90ff",
      text: "#f0f4f8",
    },
    vars: {
      "--t-bg": "#1a2a3a",
      "--t-bg-light": "#243650",
      "--t-bg-dark": "#101e2c",
      "--t-bg-darker": "#080f18",
      "--t-border-light": "#5090c0",
      "--t-border-dark": "#182840",
      "--t-titlebar-from": "#2a4a6a",
      "--t-titlebar-to": "#4a8ab8",
      "--t-titlebar-text": "#ffffff",
      "--t-accent": "#1e90ff",
      "--t-accent-hover": "#50b0ff",
      "--t-text": "#f0f4f8",
      "--t-text-muted": "#90b8d8",
      "--t-text-subtle": "#4878a0",
      "--t-marquee-bg": "#080f18",
      "--t-marquee-text": "#1e90ff",
      "--t-card-bg": "#1e3248",
      "--t-card-hover": "#284060",
      "--t-card-hover-border": "#1e90ff",
      "--t-page-from": "#0c1828",
      "--t-page-to": "#1a2a3a",
      "--t-badge-bg": "#1e90ff",
      "--t-badge-text": "#ffffff",
      "--t-inset-from": "#0c1828",
      "--t-inset-to": "#182840",
      "--t-app-bg": "#f0f4f8",
      "--t-app-text": "#1a2a3a",
      "--t-app-text-muted": "#4a6880",
      "--t-progress-from": "#2a4a6a",
      "--t-progress-to": "#1e90ff",
      "--t-defrag-used": "#1e90ff",
      "--t-defrag-fragmented": "#cc3030",
      "--t-defrag-free": "#f0f4f8",
      "--t-defrag-system": "#5080a0",
      "--t-defrag-mystery": "#70c8ff",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "6px",
      "--t-titlebar-radius": "6px",
      "--t-window-shadow": "0 6px 24px rgba(0,0,0,0.5), 0 2px 6px rgba(0,0,0,0.35)",
      "--t-dialog-shadow": "0 10px 36px rgba(0,0,0,0.55)",
      "--t-taskbar-bg": "rgba(14,30,55,0.82)",
      "--t-taskbar-blur": "blur(20px)",
      "--t-glass-bg": "rgba(100,160,220,0.14)",
      "--t-glass-blur": "blur(10px)",
      "--t-glass-border": "rgba(150,200,255,0.35)",
      "--t-scanlines": "0",
      "--t-start-btn-bg": "radial-gradient(ellipse at 50% 60%, #4090e0 0%, #1860b0 60%, #0f4090 100%)",
      "--t-start-btn-text": "#ffffff",
    },
  },
  {
    id: "dark",
    name: "Nuit profonde",
    emoji: "🌙",
    description: "Mode sombre élégant",
    preview: {
      bg: "#1a1a2e",
      titlebarFrom: "#0d0d30",
      titlebarTo: "#1a1a6e",
      titlebarText: "#a0c4ff",
      accent: "#4f8ef7",
      text: "#e0e0ff",
    },
    vars: {
      "--t-bg": "#1a1a2e",
      "--t-bg-light": "#22224a",
      "--t-bg-dark": "#0f0f23",
      "--t-bg-darker": "#080818",
      "--t-border-light": "#3a3a6e",
      "--t-border-dark": "#0d0d30",
      "--t-titlebar-from": "#0d0d30",
      "--t-titlebar-to": "#1a1a6e",
      "--t-titlebar-text": "#a0c4ff",
      "--t-accent": "#4f8ef7",
      "--t-accent-hover": "#7aaeff",
      "--t-text": "#e0e0ff",
      "--t-text-muted": "#9090bb",
      "--t-text-subtle": "#5050aa",
      "--t-marquee-bg": "#0d0d30",
      "--t-marquee-text": "#4f8ef7",
      "--t-card-bg": "#16213e",
      "--t-card-hover": "#1e2d5a",
      "--t-card-hover-border": "#4f8ef7",
      "--t-page-from": "#080818",
      "--t-page-to": "#0d0d30",
      "--t-badge-bg": "#4f8ef7",
      "--t-badge-text": "#ffffff",
      "--t-inset-from": "#0d0d30",
      "--t-inset-to": "#16213e",
      "--t-app-bg": "#0f0f23",
      "--t-app-text": "#e0e0ff",
      "--t-app-text-muted": "#9090bb",
      "--t-progress-from": "#1a1a6e",
      "--t-progress-to": "#4f8ef7",
      "--t-defrag-used": "#4f8ef7",
      "--t-defrag-fragmented": "#f74f7a",
      "--t-defrag-free": "#0d0d30",
      "--t-defrag-system": "#5050aa",
      "--t-defrag-mystery": "#a0c4ff",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "4px",
      "--t-titlebar-radius": "4px",
      "--t-window-shadow": "0 4px 20px rgba(0,0,0,0.6)",
      "--t-dialog-shadow": "0 8px 30px rgba(0,0,0,0.65)",
      "--t-taskbar-bg": "#080818",
      "--t-taskbar-blur": "none",
      "--t-glass-bg": "#1a1a2e",
      "--t-glass-blur": "none",
      "--t-glass-border": "#1a1a2e",
      "--t-scanlines": "0",
      "--t-start-btn-bg": "linear-gradient(to bottom, var(--t-bg-light), var(--t-bg))",
      "--t-start-btn-text": "#e0e0ff",
    },
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    emoji: "🌸",
    description: "A E S T H E T I C",
    preview: {
      bg: "#2d1b69",
      titlebarFrom: "#b967ff",
      titlebarTo: "#ff71ce",
      titlebarText: "#ffffff",
      accent: "#01cdfe",
      text: "#fffb96",
    },
    vars: {
      "--t-bg": "#2d1b69",
      "--t-bg-light": "#3d2480",
      "--t-bg-dark": "#1a0f40",
      "--t-bg-darker": "#0d0820",
      "--t-border-light": "#ff71ce",
      "--t-border-dark": "#b967ff",
      "--t-titlebar-from": "#b967ff",
      "--t-titlebar-to": "#ff71ce",
      "--t-titlebar-text": "#ffffff",
      "--t-accent": "#01cdfe",
      "--t-accent-hover": "#fffb96",
      "--t-text": "#fffb96",
      "--t-text-muted": "#ff71ce",
      "--t-text-subtle": "#b967ff",
      "--t-marquee-bg": "#0d0820",
      "--t-marquee-text": "#01cdfe",
      "--t-card-bg": "#3d2480",
      "--t-card-hover": "#4d2f9f",
      "--t-card-hover-border": "#01cdfe",
      "--t-page-from": "#0d0820",
      "--t-page-to": "#1a0f40",
      "--t-badge-bg": "#ff71ce",
      "--t-badge-text": "#0d0820",
      "--t-inset-from": "#1a0f40",
      "--t-inset-to": "#2d1b69",
      "--t-app-bg": "#1a0f40",
      "--t-app-text": "#fffb96",
      "--t-app-text-muted": "#ff71ce",
      "--t-progress-from": "#b967ff",
      "--t-progress-to": "#01cdfe",
      "--t-defrag-used": "#01cdfe",
      "--t-defrag-fragmented": "#ff71ce",
      "--t-defrag-free": "#0d0820",
      "--t-defrag-system": "#b967ff",
      "--t-defrag-mystery": "#fffb96",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "4px",
      "--t-titlebar-radius": "4px",
      "--t-window-shadow": "0 4px 24px rgba(185,103,255,0.4), 0 2px 8px rgba(0,0,0,0.5)",
      "--t-dialog-shadow": "0 8px 32px rgba(185,103,255,0.5)",
      "--t-taskbar-bg": "#0d0820",
      "--t-taskbar-blur": "none",
      "--t-glass-bg": "#2d1b69",
      "--t-glass-blur": "none",
      "--t-glass-border": "#2d1b69",
      "--t-scanlines": "0",
      "--t-start-btn-bg": "linear-gradient(to bottom, #b967ff, #ff71ce)",
      "--t-start-btn-text": "#ffffff",
    },
  },
  {
    id: "hacker",
    name: "Hacker",
    emoji: "💀",
    description: "We are in",
    preview: {
      bg: "#0a0a0a",
      titlebarFrom: "#001500",
      titlebarTo: "#003000",
      titlebarText: "#00ff41",
      accent: "#00ff41",
      text: "#00ff41",
    },
    vars: {
      "--t-bg": "#0a0a0a",
      "--t-bg-light": "#111111",
      "--t-bg-dark": "#050505",
      "--t-bg-darker": "#000000",
      "--t-border-light": "#00ff41",
      "--t-border-dark": "#004d14",
      "--t-titlebar-from": "#001500",
      "--t-titlebar-to": "#003000",
      "--t-titlebar-text": "#00ff41",
      "--t-accent": "#00ff41",
      "--t-accent-hover": "#00ff80",
      "--t-text": "#00ff41",
      "--t-text-muted": "#00aa2b",
      "--t-text-subtle": "#005514",
      "--t-marquee-bg": "#000000",
      "--t-marquee-text": "#00ff41",
      "--t-card-bg": "#0d0d0d",
      "--t-card-hover": "#001500",
      "--t-card-hover-border": "#00ff41",
      "--t-page-from": "#000000",
      "--t-page-to": "#000500",
      "--t-badge-bg": "#00ff41",
      "--t-badge-text": "#000000",
      "--t-inset-from": "#001500",
      "--t-inset-to": "#000800",
      "--t-app-bg": "#000000",
      "--t-app-text": "#00ff41",
      "--t-app-text-muted": "#00aa2b",
      "--t-progress-from": "#004d14",
      "--t-progress-to": "#00ff41",
      "--t-defrag-used": "#00ff41",
      "--t-defrag-fragmented": "#ff4141",
      "--t-defrag-free": "#001500",
      "--t-defrag-system": "#005514",
      "--t-defrag-mystery": "#00ffaa",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-vt323)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "0px",
      "--t-titlebar-radius": "0px",
      "--t-window-shadow": "4px 4px 0 rgba(0,255,65,0.3)",
      "--t-dialog-shadow": "6px 6px 0 rgba(0,255,65,0.35)",
      "--t-taskbar-bg": "#000000",
      "--t-taskbar-blur": "none",
      "--t-glass-bg": "#0a0a0a",
      "--t-glass-blur": "none",
      "--t-glass-border": "#0a0a0a",
      "--t-scanlines": "0.18",
      "--t-start-btn-bg": "linear-gradient(to bottom, #004d14, #001500)",
      "--t-start-btn-text": "#00ff41",
    },
  },
  {
    id: "amber",
    name: "Amber CRT",
    emoji: "🟠",
    description: "Terminal phosphore doré",
    preview: {
      bg: "#1a0e00",
      titlebarFrom: "#3d2000",
      titlebarTo: "#7a4400",
      titlebarText: "#ffb300",
      accent: "#ffb300",
      text: "#ffb300",
    },
    vars: {
      "--t-bg": "#1a0e00",
      "--t-bg-light": "#241400",
      "--t-bg-dark": "#0d0700",
      "--t-bg-darker": "#050300",
      "--t-border-light": "#c47800",
      "--t-border-dark": "#4a2c00",
      "--t-titlebar-from": "#3d2000",
      "--t-titlebar-to": "#7a4400",
      "--t-titlebar-text": "#ffb300",
      "--t-accent": "#ffb300",
      "--t-accent-hover": "#ffd040",
      "--t-text": "#e89a00",
      "--t-text-muted": "#a06800",
      "--t-text-subtle": "#5a3c00",
      "--t-marquee-bg": "#050300",
      "--t-marquee-text": "#ffb300",
      "--t-card-bg": "#1f1100",
      "--t-card-hover": "#2e1a00",
      "--t-card-hover-border": "#ffb300",
      "--t-page-from": "#050300",
      "--t-page-to": "#0d0700",
      "--t-badge-bg": "#ffb300",
      "--t-badge-text": "#000000",
      "--t-inset-from": "#0d0700",
      "--t-inset-to": "#1a0e00",
      "--t-app-bg": "#0d0700",
      "--t-app-text": "#e89a00",
      "--t-app-text-muted": "#a06800",
      "--t-progress-from": "#4a2c00",
      "--t-progress-to": "#ffb300",
      "--t-defrag-used": "#ffb300",
      "--t-defrag-fragmented": "#ff6600",
      "--t-defrag-free": "#0d0700",
      "--t-defrag-system": "#5a3c00",
      "--t-defrag-mystery": "#ffd040",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-vt323)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "0px",
      "--t-titlebar-radius": "0px",
      "--t-window-shadow": "4px 4px 0 rgba(255,179,0,0.3)",
      "--t-dialog-shadow": "6px 6px 0 rgba(255,179,0,0.35)",
      "--t-taskbar-bg": "#050300",
      "--t-taskbar-blur": "none",
      "--t-glass-bg": "#1a0e00",
      "--t-glass-blur": "none",
      "--t-glass-border": "#1a0e00",
      "--t-scanlines": "0.2",
      "--t-start-btn-bg": "linear-gradient(to bottom, #7a4400, #3d2000)",
      "--t-start-btn-text": "#ffb300",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    emoji: "🌅",
    description: "Crépuscule californien",
    preview: {
      bg: "#1a0a1e",
      titlebarFrom: "#6b1a3a",
      titlebarTo: "#c94b1a",
      titlebarText: "#ffe8c0",
      accent: "#ff6b35",
      text: "#ffe8c0",
    },
    vars: {
      "--t-bg": "#1a0a1e",
      "--t-bg-light": "#261430",
      "--t-bg-dark": "#0f0612",
      "--t-bg-darker": "#070309",
      "--t-border-light": "#9b3a6a",
      "--t-border-dark": "#4a1535",
      "--t-titlebar-from": "#6b1a3a",
      "--t-titlebar-to": "#c94b1a",
      "--t-titlebar-text": "#ffe8c0",
      "--t-accent": "#ff6b35",
      "--t-accent-hover": "#ff9060",
      "--t-text": "#ffe8c0",
      "--t-text-muted": "#c4917a",
      "--t-text-subtle": "#7a4a60",
      "--t-marquee-bg": "#070309",
      "--t-marquee-text": "#ff6b35",
      "--t-card-bg": "#221028",
      "--t-card-hover": "#30183a",
      "--t-card-hover-border": "#ff6b35",
      "--t-page-from": "#070309",
      "--t-page-to": "#0f0612",
      "--t-badge-bg": "#ff6b35",
      "--t-badge-text": "#ffffff",
      "--t-inset-from": "#0f0612",
      "--t-inset-to": "#1a0a1e",
      "--t-app-bg": "#0f0612",
      "--t-app-text": "#ffe8c0",
      "--t-app-text-muted": "#c4917a",
      "--t-progress-from": "#6b1a3a",
      "--t-progress-to": "#ff6b35",
      "--t-defrag-used": "#ff6b35",
      "--t-defrag-fragmented": "#c94b1a",
      "--t-defrag-free": "#0f0612",
      "--t-defrag-system": "#7a4a60",
      "--t-defrag-mystery": "#ffe8c0",
      "--t-font-display": "var(--font-vt323)",
      "--t-font-body": "var(--font-fredoka)",
      "--t-font-mono": "\"Courier New\", monospace",
      "--t-window-radius": "4px",
      "--t-titlebar-radius": "4px",
      "--t-window-shadow": "0 4px 20px rgba(255,107,53,0.35), 0 2px 8px rgba(0,0,0,0.5)",
      "--t-dialog-shadow": "0 8px 30px rgba(255,107,53,0.4)",
      "--t-taskbar-bg": "#070309",
      "--t-taskbar-blur": "none",
      "--t-glass-bg": "#1a0a1e",
      "--t-glass-blur": "none",
      "--t-glass-border": "#1a0a1e",
      "--t-scanlines": "0",
      "--t-start-btn-bg": "linear-gradient(to bottom, #c94b1a, #6b1a3a)",
      "--t-start-btn-text": "#ffe8c0",
    },
  },
];

export const DEFAULT_THEME_ID: ThemeId = "win95";
