services:
  app:
    build:
      context: .
      target: runner
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/data
    env_file: .env

  studio:
    build:
      context: .
      target: studio
    restart: unless-stopped
    ports:
      - "4983:4983"
    volumes:
      - db-data:/app/data
    env_file: .env
    depends_on:
      - app

volumes:
  db-data:
