FROM node:22-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
RUN apk add --no-cache python3 make g++

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY drizzle ./drizzle
COPY src/lib/db ./src/lib/db
COPY drizzle.config.ts ./
COPY tsconfig.json ./

EXPOSE 4983
CMD ["pnpm", "drizzle-kit", "studio", "--host", "0.0.0.0"]
